version: "3.9"
services:
    app:
        build:
            context: .
            target: run
        image: 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/frameworkless-basic-web-app-tiffany
        ports: 
            - 8080:8080
    test:
        build:
            context: .
            target: test
