version: "3.9"
services:
    app:
        build:
            context: .
            target: run
        image: tiffany-app
        ports: 
            - 8080:8080
    test:
        build:
            context: .
            target: test
        image: tiffany-test
