version: "3.3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/tiffany-frameworkless-basic-web-app-api:$version