@serverPrefix = http://localhost:8080

GET {{serverPrefix}}

###

GET {{serverPrefix}}/people

###

POST {{serverPrefix}}/people

{
    "Name":"DS"
}

###

POST {{serverPrefix}}/people

{
    "Name":"Mattias"
}

###

PUT {{serverPrefix}}/people/DS

{
    "Name":"DSTeoh"
}
### 

DELETE  {{serverPrefix}}/people/Mattias

