steps:
  - label: ':checkered_flag: Run Tests'
    commands: 
      - "echo 'Run the unit tests'"
      - "docker build -f Dockerfile.Test -t test ."
    agents:
      queue: grace-lab
    
  - wait 

  - label: ':gear: Build & push App'
    commands: 
      - "echo 'Build app'"
      - "docker build -f Dockerfile -t build ."
      - "aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com"
      - "docker push 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/frameworkless-basic-web-app-tiffany"
    agents:
      queue: grace-lab

