steps:
  - label: ':checkered_flag: Run Tests'
    commands: 
      - "echo 'Run the unit tests'"
      - "docker build -f Dockerfile.Test -t test ."
      - "docker rmi test -f"
    agents:
      queue: grace-lab
    
  - wait 

  - label: ':gear: Build & push App'
    commands: 
      - "echo 'Build app'"
      - "docker build -f Dockerfile -t 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/frameworkless-basic-web-app-tiffany ."
      - "docker push 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/frameworkless-basic-web-app-tiffany"
      - "docker rmi 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/frameworkless-basic-web-app-tiffany -f"
    plugins:
      - ecr#v2.3.0:
          login: true
    agents:
      queue: grace-lab

  - wait 

  - label: ':rocket: Deploy'
    command: "aws ecs update-service --cluster tiffany-cluster --service tiffany-service --force-new-deployment"
    agents:
      queue: grace-lab

