steps:
  - label: ':checkered_flag: Run Tests'
    commands: 
      - "echo 'Run the unit tests'"
      - "docker build -f Dockerfile.Test -t test ."
    agents:
      queue: grace-lab
    
  - wait 

  - label: ':gear: Build & push App'
    commands: 
      - "echo 'Build app'"
      - "docker build -f Dockerfile -t 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/frameworkless-basic-web-app-tiffany ."
      - "docker push 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/frameworkless-basic-web-app-tiffany"
    plugins:
      - ecr#v2.3.0:
        login: true
        account_ids: "138666658526"
        region: "ap-southeast-2"
    agents:
      queue: grace-lab

