steps:
  - label: ':checkered_flag: Run unit tests'
    command: ./ops/bin/unit-tests.sh
    agents:
      queue: fma-dev
    
  - label: ':shipit: Sonar scan'
    command: ./.sonarqube/scan.sh
    agents:
      queue: fma-dev
  
  - wait

  - label: ':gear: Prepare repo in ECR'
    command: ./ops/bin/prepare-ecr-repo.sh
    plugins:
      - ecr#v2.3.0:
          login: true
    agents:
      queue: fma-dev

  - wait 

  - label: ':gear: Build & push app to ECR'
    command: ./ops/bin/build-push-to-ecr.sh
    plugins:
      - ecr#v2.3.0:
          login: true
    agents:
      queue: fma-dev

  - wait 

  - label: ':checkered_flag: Run server test'
    command: ./ops/bin/server-test.sh
    agents:
      queue: fma-dev
  
  - wait 

  - label: ':rocket: Deploy to Jupiter PROD'
    branches: main
    command: 
      - ./ops/bin/jupiter-deploy.sh prod 
      - ./ops/bin/buildkite-annotation.sh
    agents:
      queue: europa-preprod-fma

  - wait: ~
    if: build.branch == "main"

  - label: ':sunglasses: Prod endpoints test'
    branches: main
    command: 
      - ./ops/bin/jupiter-smoke-test.sh
    agents:
      queue: fma-dev

notify:
  - email: "tiffany.hoang@myob.com"
    if: build.state == "failed"