steps:
  - label: ':checkered_flag: Run Tests'
    commands: 
      - "echo 'Run the unit tests'"
      - "docker build -f Dockerfile.Test -t test ."
      - "docker rmi test -f"
    agents:
      queue: grace-lab
    
  - wait 

  - label: ':gear: Build & push app to ECR'
    branches: "main"
    command: "./scripts/ops/build-push.sh"
    plugins:
      - ecr#v2.3.0:
          login: true
    agents:
      queue: grace-lab

  - wait 

  - label: ':rocket: Deploy to AWS'
    branches: "main"
    command: "aws ecs --no-cli-pager update-service --cluster tiffany-cluster --service tiffany-service --force-new-deployment"
    agents:
      queue: grace-lab

