steps:
  - label: ':checkered_flag: Run Unit Tests'
    command: ./ops/bin/unit-tests.sh
    agents:
      queue: grace-lab
    
  - label: ':shipit: Sonar scan'
    command: ./.sonarqube/scan.sh
    agents:
      queue: grace-lab

  - wait

  - label: ':gear: Prepare repo in ECR DEV'
    command: ./ops/bin/prepare-ecr-repo.sh
    plugins:
      - ecr#v2.3.0:
          login: true
    agents:
      queue: fma-dev

  - wait 

  - label: ':gear: Build & push app to ECR in DEV'
    command: ./ops/bin/build-push-to-ecr-dev.sh
    plugins:
      - ecr#v2.3.0:
          login: true
    agents:
      queue: fma-dev

  - wait 

  - label: ':rocket: Deploy to AWS DEV'
    command: ./ops/bin/deploy.sh dev
    agents:
      queue: fma-dev

  - wait 
  
  - label: ':crossed_fingers: End to End Tests'
    key: end-to-end-test
    command: ./ops/bin/e2e-tests.sh
    agents:
      queue: fma-dev
  
  - wait 
  
  - label: ':hand: Delete test deployment stack in DEV'
    command: ./ops/bin/delete-deployment-stack-dev.sh
    depends_on: end-to-end-test
    allow_dependency_failure: true
    agents:
      queue: fma-dev

  - label: ':rocket: Deploy to AWS PROD'
    # branches: main
    command: 
      - ./ops/bin/deploy.sh prod 
      - ./ops/bin/buildkite-annotation.sh
    agents:
      queue: fma-dev

  - wait: ~
    if: build.branch == "main"

  - label: ':sunglasses: Prod endpoints test'
    # branches: main
    command: 
      - ./ops/bin/smoke-test.sh
    agents:
      queue: fma-dev
  