AWSTemplateFormatVersion: 2010-09-09
Resources:
  ECSCluster:
  Type: AWS::ECS::Cluster
  Properties:
    ClusterName: tiffany-cluster
    CapacityProviders:
      - FARGATE
      - FARGATE_SPOT
    DefaultCapacityProviderStrategy:
      - CapacityProvider: FARGATE
        Weight: 1
      - CapacityProvider: FARGATE_SPOT
        Weight: 1
  Type: AWS::ECS::Service
  Properties: 
  CapacityProviderStrategy: 
    - CapacityProviderStrategyItem
  Cluster: String
  DeploymentConfiguration: 
    DeploymentConfiguration
  DeploymentController: 
    DeploymentController
  DesiredCount: Integer
  EnableECSManagedTags: Boolean
  EnableExecuteCommand: Boolean
  HealthCheckGracePeriodSeconds: Integer
  LaunchType: String
  LoadBalancers: 
    - LoadBalancer
  NetworkConfiguration: 
    NetworkConfiguration
  PlacementConstraints: 
    - PlacementConstraint
  PlacementStrategies: 
    - PlacementStrategy
  PlatformVersion: String
  PropagateTags: String
  Role: String
  SchedulingStrategy: String
  ServiceArn: String
  ServiceName: tiffany-service
  ServiceRegistries: 
    - ServiceRegistry
  Tags: 
    - Tag
  TaskDefinition: String
  Type: AWS::ECS::TaskDefinition
  Properties: 
    ContainerDefinitions: 
      - 
        Name: 
          Ref: "tiff-app"
        Image: "138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/frameworkless-basic-web-app-tiffany:latest"
        Cpu: 256
        PortMappings: 
          - ContainerPort: "8080"
          - HostPort: "8080"
        Memory: 512
        Essential: true
