AWSTemplateFormatVersion: 2010-09-09
Parameters:
  version:
    Type: String
  vpcId:
    Type: String
  subnet1:
    Type: String
  subnet2: 
    Type: String
  certificate:
    Type: String
  domainName:
    Type: String
  CNAMERecordName:
    Type: String
  CNAMERecordValue:
    Type: String
  ECRAccount:
    Type: String
Resources:
  ALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow all myob melb and syd ip to access Application Load Balancer
      GroupName: tiffany-api-sg-lb
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 443
          CidrIp: 203.34.100.0/24
          Description: Melbourne DC
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 443
          CidrIp: 49.255.41.116/30
          Description: Sydney Kent Street
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 443
          CidrIp: 124.254.104.108/30
          Description: Melbourne Cremorne
      VpcId: !Ref vpcId
  ApplicationSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow load balancer to access application
      GroupName: tiffany-api-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupName: tiffany-api-sg-lb
          Description: tiffany-api-sg-lb
      VpcId: !Ref vpcId
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: tiffany-api-load-balancer
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref ALBSecurityGroup
      Subnets: 
        - !Ref subnet1
        - !Ref subnet2
      Type: application
  ListenerForHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: "redirect"
          RedirectConfig: 
            Protocol: "HTTPS"
            Port: 443
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
  ListenerForHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      Certificates: 
        - CertificateArn: !Ref certificate
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true
      Name: tiffany-api-target-group
      TargetType: ip
      VpcId: !Ref vpcId
      Protocol: HTTP
      Port: 8080
    DependsOn: LoadBalancer
  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties: 
      Family: "tiffany-api-task"
      TaskRoleArn: "ecsTaskExecutionRole"
      ExecutionRoleArn: "ecsTaskExecutionRole"
      NetworkMode: "awsvpc"
      RequiresCompatibilities: 
        - "FARGATE"
      Cpu: "256"
      Memory: "0.5GB"
      ContainerDefinitions: 
        - Name: "tiff-app-api"
          Image: !Sub ${ECRAccount}/tiffany-frameworkless-basic-web-app-api:${version}
          PortMappings: 
            - ContainerPort: 8080
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - "FARGATE"
      ClusterName: "tiffany-api-cluster"
  ECSService:
    Type: AWS::ECS::Service
    Properties: 
      LaunchType: FARGATE
      Cluster: !Ref ECSCluster
      DeploymentConfiguration: 
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 2
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - !Ref ApplicationSecurityGroup
          Subnets: 
            - !Ref subnet1
      ServiceName: tiffany-api-service
      TaskDefinition: !Ref TaskDefinition 
      LoadBalancers:
      - TargetGroupArn: !Ref TargetGroup
        ContainerPort: 8080
        ContainerName: tiff-app-api
    DependsOn: 
    - ListenerForHTTP
    - ListenerForHTTPS
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: !Ref domainName
  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !GetAtt HostedZone.Id
      Comment: Zone apex alias targeted to LoadBalancer.
      RecordSets:
      - Name: !Ref domainName
        Type: A
        AliasTarget:
          HostedZoneId: !GetAtt 'LoadBalancer.CanonicalHostedZoneID'
          DNSName: !GetAtt 'LoadBalancer.DNSName'
  CNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !GetAtt HostedZone.Id
      Name: !Ref CNAMERecordName
      ResourceRecords:
      - !Ref CNAMERecordValue
      Type: CNAME
      TTL: 300
Outputs:
  HostedZone:
    Description: Hosted Zone
    Value: !Ref HostedZone
  ZoneServers:
    Description: Zone Servers
    Value: !Join [',', !GetAtt HostedZone.NameServers]
    Export:
      Name: !Sub "${AWS::StackName}-NameServers"