AWSTemplateFormatVersion: 2010-09-09
Parameters:
  version:
    Type: String
Resources:
  ALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow all myob melb and syd ip to access Application Load Balancer
      GroupName: tiffany-api-sg-lb
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 443
          CidrIp: 203.34.100.0/24
          Description: Melbourne DC
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 443
          CidrIp: 49.255.41.116/30
          Description: Sydney Kent Street
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 443
          CidrIp: 124.254.104.108/30
          Description: Melbourne Cremorne
      VpcId: vpc-d88094bf
  ApplicationSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow load balancer to access application
      GroupName: tiffany-api-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupName: tiffany-api-sg-lb
          Description: tiffany-api-sg-lb
      VpcId: vpc-d88094bf
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: tiffany-api-load-balancer
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref ALBSecurityGroup
      Subnets: 
        - subnet-0ecc2546
        - subnet-316e9257
      Type: application
  ListenerForHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        - Type: "redirect"
          RedirectConfig: 
            Protocol: "HTTPS"
            Port: 443
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
  ListenerForHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      Certificates: 
        - CertificateArn: arn:aws:acm:ap-southeast-2:138666658526:certificate/026583fe-93ca-4b50-9735-575fcf92a19d
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true
      Name: tiffany-api-target-group
      TargetType: ip
      VpcId: vpc-d88094bf
      Protocol: HTTP
      Port: 8080
    DependsOn: LoadBalancer
  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties: 
      Family: "tiffany-api-task"
      TaskRoleArn: "ecsTaskExecutionRole"
      ExecutionRoleArn: "ecsTaskExecutionRole"
      NetworkMode: "awsvpc"
      RequiresCompatibilities: 
        - "FARGATE"
      Cpu: "256"
      Memory: "0.5GB"
      ContainerDefinitions: 
        - Name: "tiff-app-api"
          Image: !Sub 138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/tiffany-frameworkless-basic-web-app-api:${version}
          PortMappings: 
            - ContainerPort: 8080
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - "FARGATE"
      ClusterName: "tiffany-api-cluster"
  ECSService:
    Type: AWS::ECS::Service
    Properties: 
      LaunchType: FARGATE
      Cluster: !Ref ECSCluster
      DeploymentConfiguration: 
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 2
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - !Ref ApplicationSecurityGroup
          Subnets: 
            - subnet-0ecc2546
      ServiceName: tiffany-api-service
      TaskDefinition: !Ref TaskDefinition 
      LoadBalancers:
      - TargetGroupArn: !Ref TargetGroup
        ContainerPort: 8080
        ContainerName: tiff-app-api
    DependsOn: 
    - ListenerForHTTP
    - ListenerForHTTPS
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties: 
      Name: tiffany.fma.lab.myobdev.com
  DNSRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !GetAtt HostedZone.Id
      Comment: Zone apex alias targeted to LoadBalancer.
      RecordSets:
      - Name: tiffany.fma.lab.myobdev.com
        Type: A
        AliasTarget:
          HostedZoneId: !GetAtt 'LoadBalancer.CanonicalHostedZoneID'
          DNSName: !GetAtt 'LoadBalancer.DNSName'
  CNAMERecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !GetAtt HostedZone.Id
      Name: _4956d49111f1819354882aa5f1f592fb.tiffany.fma.lab.myobdev.com
      ResourceRecords:
      - _eae68a1120e0e48d65223094bd79688e.bbfvkzsszw.acm-validations.aws.
      Type: CNAME
      TTL: 300
Outputs:
  DomainName: 
    Value: !GetAtt HostedZone.NameServers
