AWSTemplateFormatVersion: 2010-09-09
Resources:
  ALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow all myob melb and syd ip to access Application Load Balancer
      GroupName: tiffany-api-sg-lb
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 203.34.100.0/24
          Description: Melbourne DC
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 49.255.41.116/30
          Description: Sydney Kent Street
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 124.254.104.108/30
          Description: Melbourne Cremorne
      VpcId: vpc-d88094bf
  ApplicationSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow load balancer to access application
      GroupName: tiffany-api-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupName: tiffany-api-sg-lb
          Description: tiffany-api-sg-lb
      VpcId: vpc-d88094bf
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Name: tiffany-api-load-balancer
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref ALBSecurityGroup
      Subnets: 
        - subnet-0ecc2546
        - subnet-316e9257
      Type: application
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      Certificates: 
        - arn:aws:acm:ap-southeast-2:138666658526:certificate/026583fe-93ca-4b50-9735-575fcf92a19d
      DefaultActions: 
        - Type: "forward"
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckEnabled: true
      Name: tiffany-api-target-group
      TargetType: ip
      VpcId: vpc-d88094bf
      Protocol: HTTP
      Port: 80
    DependsOn: LoadBalancer
  TaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties: 
        Family: "tiffany-api-task"
        TaskRoleArn: "ecsTaskExecutionRole"
        ExecutionRoleArn: "ecsTaskExecutionRole"
        NetworkMode: "awsvpc"
        RequiresCompatibilities: 
            - "FARGATE"
        CPU: "256"
        Memory: "0.5GB"
        ContainerDefinitions: 
            - Name: "tiff-app-api"
              Image: "138666658526.dkr.ecr.ap-southeast-2.amazonaws.com/tiffany-frameworkless-basic-web-app-api:latest"
              PortMappings: 
                - ContainerPort: 8080
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties: 
      CapacityProviders: 
        - "FARGATE"
      ClusterName: "tiffany-api-cluster"
  ECSService:
    Type: AWS::ECS::Service
    Properties: 
      LaunchType: FARGATE
      Cluster: !Ref ECSCluster
      DeploymentConfiguration: 
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      DesiredCount: 2
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: 
            - !Ref ApplicationSecurityGroup
          Subnets: 
            - subnet-0ecc2546
      ServiceName: tiffany-api-service
      TaskDefinition: !Ref TaskDefinition 
      LoadBalancers:
      - TargetGroupArn: !Ref TargetGroup
        ContainerPort: 8080
        ContainerName: tiff-app-api
      Cluster: !Ref ECSCluster
    DependsOn: Listener
       