AWSTemplateFormatVersion: 2010-09-09
Parameters:
  domainName:
    Type: String
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
        Properties:
          DomainName: domainName
          ValidationMethod: DNS