AWSTemplateFormatVersion: 2010-09-09
Description: Repository for web application api image
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: tiffany-frameworkless-basic-web-app-api

