@serverPrefix = http://localhost:8080
@SECRET=secret
@header = Authorization: Basic {{SECRET}}

GET {{serverPrefix}}
{{header}}
###

GET {{serverPrefix}}
###

GET {{serverPrefix}}/people
{{header}}
###


GET {{serverPrefix}}/people
###

POST {{serverPrefix}}/people
{{header}}

{
    "Name":"DS"
}

###

POST {{serverPrefix}}/people
{{header}}

{
    "Name":"Mattias"
}

###

PUT {{serverPrefix}}/people/DS
{{header}}

{
    "Name":"DSTeoh"
}

### 

DELETE {{serverPrefix}}/people/Mattias
{{header}}
###

GET {{serverPrefix}}/invalidPath
{{header}}
###

POST {{serverPrefix}}
{{header}}
###

PATCH {{serverPrefix}}/people
{{header}}
###

GET {{serverPrefix}}/health
###